// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_server_app_dev_final.Data;

#nullable disable

namespace web_server_app_dev_final.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251205080952_AddNewGameData")]
    partial class AddNewGameData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_server_app_dev_final.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Platforms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://cdn.cloudflare.steamstatic.com/steam/apps/1672970/library_600x900_2x.jpg",
                            Description = "Build anything you can imagine in this infinite sandbox.",
                            Developer = "Mojang Studios",
                            Genres = "Sandbox,Survival",
                            IsFeatured = true,
                            Platforms = "PC,PS5,NSW",
                            Rating = 10.0m,
                            ReleaseYear = 2011,
                            ReviewDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "The most important game ever made.",
                            Reviewer = "Ethan R",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://cdn.cloudflare.steamstatic.com/steam/apps/2357570/library_600x900_2x.jpg",
                            Developer = "Blizzard Entertainment",
                            Genres = "Shooter,Multiplayer",
                            IsFeatured = false,
                            Platforms = "PC,PS5",
                            Rating = 5.0m,
                            ReleaseYear = 2022,
                            ReviewDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "A disappointing sequel that removed more than it added.",
                            Reviewer = "Ethan R",
                            Title = "Overwatch 2"
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "https://cdn.cloudflare.steamstatic.com/steam/apps/264710/library_600x900_2x.jpg",
                            Developer = "Unknown Worlds",
                            Genres = "Survival,Adventure",
                            IsFeatured = false,
                            Platforms = "PC,PS5",
                            Rating = 9.0m,
                            ReleaseYear = 2018,
                            ReviewDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Terrifying ocean survival that nails atmosphere.",
                            Reviewer = "Ethan R",
                            Title = "Subnautica"
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/library_600x900_2x.jpg",
                            Developer = "Wube Software",
                            Genres = "Simulation,Strategy",
                            IsFeatured = false,
                            Platforms = "PC",
                            Rating = 9.0m,
                            ReleaseYear = 2020,
                            ReviewDate = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "The factory must grow.",
                            Reviewer = "Ethan R",
                            Title = "Factorio"
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "https://tse1.mm.bing.net/th/id/OIP.4D_3COBMYkVMCYYWQ7KCLwHaLH?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
                            Developer = "Afterthought LLC",
                            Genres = "Simulation,Survival,Horror",
                            IsFeatured = false,
                            Platforms = "PC",
                            Rating = 10.0m,
                            ReleaseYear = 2015,
                            ReviewDate = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Withstand what the island throws at you, no matter the cost.",
                            Reviewer = "Ella S",
                            Title = "The Isle"
                        },
                        new
                        {
                            Id = 6,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
                            Developer = "Rockstar Games",
                            Genres = "Open World,Shooter,RPG",
                            IsFeatured = false,
                            Platforms = "PC",
                            Rating = 10.0m,
                            ReleaseYear = 2018,
                            ReviewDate = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "I have a plan.",
                            Reviewer = "Ella S",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 7,
                            CoverImageUrl = "https://i1.sndcdn.com/artworks-EioFkgzPYZ8dFdQc-g71gJA-t1080x1080.jpg",
                            Developer = "Funkin' Crew",
                            Genres = "Rhythm,Music",
                            IsFeatured = false,
                            Platforms = "PC",
                            Rating = 10.0m,
                            ReleaseYear = 2019,
                            ReviewDate = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Rhythm game perfection.",
                            Reviewer = "Ella S",
                            Title = "Friday Night Funkin'"
                        },
                        new
                        {
                            Id = 8,
                            CoverImageUrl = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/443ce950-f8e1-4188-b51b-720aba16a967/ddqggjm-b7fdd5f9-f4bb-4cc3-bddd-e7b3071245bf.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzQ0M2NlOTUwLWY4ZTEtNDE4OC1iNTFiLTcyMGFiYTE2YTk2N1wvZGRxZ2dqbS1iN2ZkZDVmOS1mNGJiLTRjYzMtYmRkZC1lN2IzMDcxMjQ1YmYuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.LRlnnP2xMXcYpAJ1jrWncoEkNpUAZGMHTd5WySPQ4wI",
                            Developer = "Scott Cawthon",
                            Genres = "Horror",
                            IsFeatured = false,
                            Platforms = "PC,Moblie,Console",
                            Rating = 10.0m,
                            ReleaseYear = 2014,
                            ReviewDate = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Single handedly the best horror franchise out there.",
                            Reviewer = "Ella S",
                            Title = "Five Nights At Freddy's (Series)"
                        },
                        new
                        {
                            Id = 9,
                            CoverImageUrl = "https://archives.bulbagarden.net/media/upload/d/dc/Black_EN_boxart.png",
                            Developer = "Game Freak",
                            Genres = "RPG",
                            IsFeatured = false,
                            Platforms = "DS",
                            Rating = 10.0m,
                            ReleaseYear = 2010,
                            ReviewDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Game Freak's pinnacle of Pokemon!",
                            Reviewer = "Ethan G",
                            Title = "Pokemon Black Version"
                        },
                        new
                        {
                            Id = 10,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/dc/Utopia_%28video_game%29_boxart.jpg",
                            Developer = "Mattel Electronics",
                            Genres = "Strategy",
                            IsFeatured = false,
                            Platforms = "Intellivision",
                            Rating = 8.0m,
                            ReleaseYear = 1982,
                            ReviewDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Civilization's great-granddaddy.",
                            Reviewer = "Ethan G",
                            Title = "Utopia"
                        },
                        new
                        {
                            Id = 11,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e6/Worms_WMD_cover_art.jpg",
                            Developer = "",
                            Genres = "Strategy, Party, Physics",
                            IsFeatured = false,
                            Platforms = "PC, Switch, XBOX, PS4, IOS, Android",
                            Rating = 6.0m,
                            ReleaseYear = 2016,
                            ReviewDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "Worms is fun, but this one disappoints.",
                            Reviewer = "Ethan G",
                            Title = "Worms WMD"
                        },
                        new
                        {
                            Id = 12,
                            CoverImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d5/Civilization_VII_cover.png",
                            Developer = "Firaxis Games",
                            Genres = "Strategy",
                            IsFeatured = false,
                            Platforms = "Cross-Platform",
                            Rating = 6.0m,
                            ReleaseYear = 2025,
                            ReviewDate = new DateTime(2025, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewText = "An unworthy successor to 6.",
                            Reviewer = "Ethan G",
                            Title = "Civilization 7"
                        });
                });

            modelBuilder.Entity("web_server_app_dev_final.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Creator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
